#!/bin/sh

set -eu

# Get buildDir and ensure CWD is location of build script
origDir=$( pwd -P )
scriptDir=$( CDPATH='' cd -- "$( dirname -- "$0" )" && pwd -P )
if [ "$origDir" = "$scriptDir" ]; then
	buildDir="$scriptDir/.build"
else
	buildDir="$origDir"
	cd "$scriptDir"
fi


. scripts/error.sh


printHelp( )
{
	helpText="
  build [<style> [<target> ...]]

      Build target(s) using style.
      If no target is provided, all targets are build.
      If no style is provided, all targets are build deployment style.


  build -t[argets]

      List available targets.


  build -s[tyles]

      List available styles.


  build -h[elp]

      Show this help screen.
"
	printf '%s' "$helpText"
}


printHelpAndExit( )
{
	printHelp >&2
	exit 1
}


printTargetsAndExit( )
{
	for targetDir in targets/*
	do
		[ -d "$targetDir" ] || continue
		printf '%s\n' "$( basename -- "$targetDir" )"
	done
	exit 0
}


printStylesAndExit( )
{
	for styleFile in styles/*.txt
	do
		[ -f "$styleFile" ] || continue
		styleName=$( basename -- "$styleFile" .txt )
		case $styleName in
			_*) continue ;;
		esac
		printf '%s\n' "$styleName"
	done
	exit 0
}


case "${1:-}" in
	-help|-h)
		[ "$#" -eq 1 ] || printHelpAndExit
		printHelp
		exit 0
		;;

	-targets|-t)
		[ "$#" -eq 1 ] || printHelpAndExit
		printTargetsAndExit
		;;

	-styles|-s)
		[ "$#" -eq 1 ] || printHelpAndExit
		printStylesAndExit
		;;

	-*)
		printHelpAndExit
		;;
esac


styleName=${1:-}
if [ -z "$styleName" ]
then
	styleName=deploy
else
	shift
fi

styleFile=$styleName
case "$styleFile" in
	*/*) ;;
	*.txt) styleFile="styles/$styleFile" ;;
	*) styleFile="styles/$styleName.txt" ;;
esac

if [ ! -f "$styleFile" ]
then
	printErrorAndExit "Style not found: $styleFile"
fi


. scripts/style.sh
. scripts/quote.sh



styleSettings=$( expandStyle "$styleFile" )
buildSettings=""
if [ -n "$styleSettings" ]
then
	oldIFS=$IFS
	IFS='
'
	for setting in $styleSettings
	do
		quoted=$( quote "$setting" )
		if [ -z "$buildSettings" ]
		then
			buildSettings=$quoted
		else
			buildSettings="$buildSettings $quoted"
		fi
	done
	IFS=$oldIFS
fi

if [ "$#" -eq 0 ]
then
	set --
	for targetDir in targets/*
	do
		[ -d "$targetDir" ] || continue
		set -- "$@" "$( basename -- "$targetDir" )"
	done
	if [ "$#" -eq 0 ]
	then
		printErrorAndExit "No targets found"
	fi
else
	for target in "$@"
	do
		if [ ! -d "targets/$target" ]
		then
			printErrorAndExit "Target not found: $target"
		fi
	done
fi
